/**
 * generated by Xtext
 */
package org.alma.mde.statemachine.ui.contentassist;

import org.alma.mde.statemachine.ui.contentassist.AbstractZhuProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ZhuProposalProvider extends AbstractZhuProposalProvider {
}
