/*
 * generated by Xtext
 */
package org.alma.mde.statemachine.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ZhuAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/alma/mde/statemachine/parser/antlr/internal/InternalZhu.tokens");
	}
}
