/*
 * generated by Xtext
 */
package org.alma.mde.statemachine.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.alma.mde.statemachine.services.ZhuGrammarAccess;

public class ZhuParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ZhuGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.alma.mde.statemachine.parser.antlr.internal.InternalZhuParser createParser(XtextTokenStream stream) {
		return new org.alma.mde.statemachine.parser.antlr.internal.InternalZhuParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "StateMachine";
	}
	
	public ZhuGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ZhuGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
