/*
 * generated by Xtext
 */
package org.alma.mde.statemachine;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ZhuUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.alma.mde.statemachine.ui.internal.ZhuActivator.getInstance().getInjector("org.alma.mde.statemachine.Zhu");
	}
	
}
