/*
 * generated by Xtext
 */
package org.alma.mde.statemachine.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.alma.mde.statemachine.ui.internal.ZhuActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ZhuExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ZhuActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ZhuActivator.getInstance().getInjector(ZhuActivator.ORG_ALMA_MDE_STATEMACHINE_ZHU);
	}
	
}
