/*
 * generated by Xtext
 */
package org.alma.mde.statemachine;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ZhuRuntimeModule extends org.alma.mde.statemachine.AbstractZhuRuntimeModule {

}
