/**
 * generated by Xtext
 */
package org.alma.mde.statemachine.validation;

import org.alma.mde.statemachine.validation.AbstractZhuValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ZhuValidator extends AbstractZhuValidator {
}
