/*
 * generated by Xtext
 */
package org.alma.mde.statemachine.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ZhuUiModule extends org.alma.mde.statemachine.ui.AbstractZhuUiModule {
	public ZhuUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
